on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip3 install matplotlib --break-system-packages
      - run: pip3 install numpy --break-system-packages
